---
- name: OpenShift Cluster Raport Generator (fetch information)
  hosts: localhost
  become: false

  vars_files:
    - ./variables/main.yaml
    - ./variables/ocp.yaml

  module_defaults:
    group/kubernetes.core.k8s:
      host: "{{ ocp_host }}"
      validate_certs: "{{ ocp_verify_ssl }}"
    kubernetes.core.k8s_auth:
      host: "{{ ocp_host }}"
      validate_certs: "{{ ocp_verify_ssl }}"

  pre_tasks:
    - name: Log in (obtain access token)
      kubernetes.core.k8s_auth:
        username: "{{ ocp_username }}"
        password: "{{ ocp_password }}"
      register: ocp_auth_results
      tags:
        - always

    - name: Set required variables
      ansible.builtin.set_fact:
        ocp_api_token: "{{ ocp_auth_results.openshift_auth.api_key }}"
        ocprg_result_dir: "{{ ocp_host.split('.')[1] }}-result-{{ ansible_date_time.date }}"
      tags:
        - always

    - name: Create result directory
      ansible.builtin.file:
        path: "{{ ocprg_result_dir }}"
        state: directory
        mode: "0755"

  roles:
    - cluster_info
    - nodes
    - pods

  post_tasks:
    - name: If login succeeded, try to log out (revoke access token)
      kubernetes.core.k8s_auth:
        state: absent
        api_key: "{{ ocp_api_token }}"
      when: ocp_api_token is defined
      ignore_errors: true
      tags:
        - always

    - name: Create tar archive with results
      ansible.builtin.archive:
        path: "{{ ocprg_result_dir }}"
        dest: "{{ ocprg_result_dir }}.tar.gz"
        remove: "{{ ocpgr_result_dir_remove }}"
      tags:
        - always
