---
- name: OpenShift Cluster Raport Generator (fetch information)
  hosts: localhost
  become: false

  vars_files:
    - ./variables/main.yaml
    - ./variables/ocp_credentials.yaml

  module_defaults:
    group/kubernetes.core.k8s:
      host: "{{ ocp_host }}"
      validate_certs: "{{ ocp_verify_ssl }}"
    kubernetes.core.k8s_auth:
      host: "{{ ocp_host }}"
      validate_certs: "{{ ocp_verify_ssl }}"

  pre_tasks:
    - name: Log in (obtain access token)
      kubernetes.core.k8s_auth:
        username: "{{ ocp_username }}"
        password: "{{ ocp_password }}"
      register: ocp_auth_results
      tags:
        - always

    - name: Set access tokent to OCP
      ansible.builtin.set_fact:
        ocp_api_token: "{{ ocp_auth_results.openshift_auth.api_key }}"
      tags:
        - always

  roles:
    - cluster_info
    - nodes

  post_tasks:
    - name: If login succeeded, try to log out (revoke access token)
      kubernetes.core.k8s_auth:
        state: absent
        api_key: "{{ ocp_api_token }}"
      when: ocp_api_token is defined
      tags:
        - always
