---
- name: Fetch a list of nodes
  kubernetes.core.k8s_info:
    kind: Node
    api_key: "{{ ocp_api_token }}"
  when: ocpgr_feature_nodes
  register: nodes_info
  tags:
    - nodes

- name: Save nodes information to file
  ansible.builtin.copy:
    content: "{{ nodes_info.resources[0] }}"
    dest: "{{ ocprg_result_dir }}/{{ cluster_nodes_file_name }}"
    mode: "0644"
  when:
    - ocpgr_feature_nodes
    - nodes_info.resources is defined
  tags:
    - nodes
