---
- name: Fetch a list of nodes
  kubernetes.core.k8s_info:
    kind: Node
    api_key: "{{ ocp_api_token }}"
  register: nodes_info

- name: Generate node list information
  ansible.builtin.blockinfile:
    path: "{{ cr_filename }}"
    block: "{{ lookup('template', 'nodes.j2') }}"
    marker: ""
  vars:
    jmesquery: >-
      resources[*].{
        name: metadata.name, 
        time: metadata.creationTimestamp, 
        version: status.nodeInfo.kubeletVersion,
        conditions: status.conditions[?reason=='KubeletReady'].type,
        labels: metadata.labels
      }
    nodes: "{{ nodes_info | community.general.json_query(jmesquery) }}"
    datatime: "{{ ansible_date_time.date }}"